### ISSUE TITLE
Trailsense package returns error

### ISSUE THREAD

**Issue by Popolechien** [offspot/demo#15]
Steps to reproduce: 

* Go to https://preppers.demo.hotspot.kiwix.org/
* Click on the Trailsense app
* Error: `This site can’t provide a secure connectioncom.kylecorry.trail_sense.preppers.demo.hotspot.kiwix.org sent an invalid response.
ERR_SSL_PROTOCOL_ERROR`

Note: the survival manual app works fine

**Comment by kelson42** [comment]
Seems that TLS is not activated at all for this subdomain.

**Comment by rgaudin** [comment]
This is due to the underscore(s) in the domain name.
I fixed it by  changing the domains (using dashes) in offspot-config. @Popolechien you'll need to update the image(s) for it to be fixed in the demo.
